server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # ESTA É A LINHA QUE RESOLVE O PROBLEMA:
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuração para as imagens (se o Nginx também as servir)
    location /fotos/ {
        alias /app/upload/presentes/;
    }
}