// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChaDeBebe.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322052748_UsuarioCha")]
    partial class UsuarioCha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChaDeBebeEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("ChasDeBebe");
                });

            modelBuilder.Entity("Presente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChaDeBebeEventoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChaDeBebeEventoId");

                    b.ToTable("Presentes");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("UsuarioChaDeBebe", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ChaDeBebeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ChaDeBebeEventoId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "ChaDeBebeId");

                    b.HasIndex("ChaDeBebeEventoId");

                    b.ToTable("UsuarioChaDeBebe");
                });

            modelBuilder.Entity("ChaDeBebeEvento", b =>
                {
                    b.HasOne("Usuario", "Admin")
                        .WithMany("MeusChas")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Presente", b =>
                {
                    b.HasOne("ChaDeBebeEvento", null)
                        .WithMany("Presentes")
                        .HasForeignKey("ChaDeBebeEventoId");
                });

            modelBuilder.Entity("UsuarioChaDeBebe", b =>
                {
                    b.HasOne("ChaDeBebeEvento", "ChaDeBebeEvento")
                        .WithMany()
                        .HasForeignKey("ChaDeBebeEventoId");

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChaDeBebeEvento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChaDeBebeEvento", b =>
                {
                    b.Navigation("Presentes");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("MeusChas");
                });
#pragma warning restore 612, 618
        }
    }
}
