// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChaDeBebe.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324195954_Reserva")]
    partial class Reserva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChaDeBebeEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("ChasDeBebe");
                });

            modelBuilder.Entity("Presente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaDeBebeEventoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("LinkSugerido")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImage")
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantidadeTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ChaDeBebeEventoId");

                    b.ToTable("Presentes");
                });

            modelBuilder.Entity("Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaDeBebeEventoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PresenteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<int?>("UsuarioChaDeBebeChaDeBebeId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioChaDeBebeUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChaDeBebeEventoId");

                    b.HasIndex("PresenteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioChaDeBebeUsuarioId", "UsuarioChaDeBebeChaDeBebeId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("UsuarioChaDeBebe", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ChaDeBebeId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "ChaDeBebeId");

                    b.HasIndex("ChaDeBebeId");

                    b.ToTable("UsuarioChaDeBebe");
                });

            modelBuilder.Entity("ChaDeBebeEvento", b =>
                {
                    b.HasOne("Usuario", "Admin")
                        .WithMany("MeusChas")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Presente", b =>
                {
                    b.HasOne("ChaDeBebeEvento", "ChaDeBebeEvento")
                        .WithMany("Presentes")
                        .HasForeignKey("ChaDeBebeEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChaDeBebeEvento");
                });

            modelBuilder.Entity("Reserva", b =>
                {
                    b.HasOne("ChaDeBebeEvento", "ChaDeBebeEvento")
                        .WithMany()
                        .HasForeignKey("ChaDeBebeEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Presente", "Presente")
                        .WithMany("Reservas")
                        .HasForeignKey("PresenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UsuarioChaDeBebe", null)
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioChaDeBebeUsuarioId", "UsuarioChaDeBebeChaDeBebeId");

                    b.Navigation("ChaDeBebeEvento");

                    b.Navigation("Presente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UsuarioChaDeBebe", b =>
                {
                    b.HasOne("ChaDeBebeEvento", "ChaDeBebe")
                        .WithMany()
                        .HasForeignKey("ChaDeBebeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChaDeBebe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChaDeBebeEvento", b =>
                {
                    b.Navigation("Presentes");
                });

            modelBuilder.Entity("Presente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("MeusChas");
                });

            modelBuilder.Entity("UsuarioChaDeBebe", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
